### ISSUE TITLE
Front-end build failure

### ISSUE THREAD

**Issue by shah-rushi** [aws-samples/lambda-refarch-imagerecognition#126]
Hi,

The Front-end build fails to locate "@aws-amplify/cache" and ends with an error. Would you please be able to look into this when you have the bandwidth?

Thank you,
Rushi

`2021-04-02T17:05:24.062Z [INFO]: # Executing command: npm run build
2021-04-02T17:05:24.230Z [INFO]: > photo-sharing-webapp-react@0.1.1 build /codebuild/output/src310315486/src/lambda-refarch-imagerecognition/src/react-frontend
                                 > react-scripts build
2021-04-02T17:05:25.338Z [INFO]: Creating an optimized production build...
2021-04-02T17:05:30.026Z [INFO]: Failed to compile.
2021-04-02T17:05:30.027Z [INFO]: ./node_modules/@aws-amplify/api/lib-esm/API.js
                                 Cannot find module: '@aws-amplify/cache'. Make sure this package is installed.
                                 You can install this package by running: npm install @aws-amplify/cache.
2021-04-02T17:05:30.042Z [WARNING]: npm
2021-04-02T17:05:30.043Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
2021-04-02T17:05:30.045Z [WARNING]: npm
2021-04-02T17:05:30.045Z [WARNING]: ERR! photo-sharing-webapp-react@0.1.1 build: `react-scripts build`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the photo-sharing-webapp-react@0.1.1 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-04-02T17:05:30.051Z [WARNING]: 
2021-04-02T17:05:30.051Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2021-04-02T17_05_30_045Z-debug.log
2021-04-02T17:05:30.051Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [
                                 1 verbose cli   '/root/.nvm/versions/node/v12.21.0/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v12.21.0/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build'
                                 1 verbose cli ]
                                 2 info using npm@6.14.11
                                 3 info using node@v12.21.0
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle photo-sharing-webapp-react@0.1.1~prebuild: photo-sharing-webapp-react@0.1.1
                                 6 info lifecycle photo-sharing-webapp-react@0.1.1~build: photo-sharing-webapp-react@0.1.1
                                 7 verbose lifecycle photo-sharing-webapp-react@0.1.1~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle photo-sharing-webapp-react@0.1.1~build: PATH: /root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src310315486/src/lambda-refarch-imagerecognition/src/react-frontend/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/.nvm/versions/node/v12.21.0/bin:/root/.local/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools
                                 9 verbose lifecycle photo-sharing-webapp-react@0.1.1~build: CWD: /codebuild/output/src310315486/src/lambda-refarch-imagerecognition/src/react-frontend
                                 10 silly lifecycle photo-sharing-webapp-react@0.1.1~build: Args: [ '-c', 'react-scripts build' ]
                                 11 silly lifecycle photo-sharing-webapp-react@0.1.1~build: Returned: code: 1  signal: null
                                 12 info lifecycle photo-sharing-webapp-react@0.1.1~build: Failed to exec build script
                                 13 verbose stack Error: photo-sharing-webapp-react@0.1.1 build: `react-scripts build`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:314:20)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:314:20)
                                 13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
                                 14 verbose pkgid photo-sharing-webapp-react@0.1.1
                                 15 verbose cwd /codebuild/output/src310315486/src/lambda-refarch-imagerecognition/src/react-frontend
                                 16 verbose Linux 4.14.219-119.340.amzn1.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v12.21.0/bin/node" "/root/.nvm/versions/node/v12.21.0/bin/npm" "run" "build"
                                 18 verbose node v12.21.0
                                 19 verbose npm  v6.14.11
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error photo-sharing-webapp-react@0.1.1 build: `react-scripts build`
                                 22 error Exit status 1
                                 23 error Failed at the photo-sharing-webapp-react@0.1.1 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2021-04-02T17:05:30.054Z [ERROR]: !!! Build failed
2021-04-02T17:05:30.054Z [ERROR]: !!! Non-Zero Exit Code detected`

**Comment by maxatv123** [comment]
Same error is happening to me, did you find out what the issue was? seems to pass all steps until the end with the non-zero exit code detected
[log.txt](https://github.com/aws-samples/lambda-refarch-imagerecognition/files/6298604/log.txt)

**Comment by Haks1** [comment]
Same error here

**Comment by SteveSultan** [comment]
same error

**Comment by typex1** [comment]
Same error, my root cause analysis showed it is due to conflicting and partially incomplete aws-amplify dependencies in src/react-frontend/package.json. I forked the original repo and did the needed changes, for my it works now! My repo is https://github.com/typex1/lambda-refarch-imagerecognition

**Comment by liangyimingcom** [comment]
> Same error, my root cause analysis showed it is due to conflicting and partially incomplete aws-amplify dependencies in src/react-frontend/package.json. I forked the original repo and did the needed changes, for my it works now! My repo is https://github.com/typex1/lambda-refarch-imagerecognition

It's worked from your repo, thank you a lot. :)

**Comment by vaibhavbudhlani** [comment]
Hello typex1 and llangyimingcom this llink is  https://github.com/typex1/lambda-refarch-imagerecognition not working. Can you provide the correct repo.

Thanks

**Comment by typex1** [comment]
> Hello typex1 and llangyimingcom this llink is https://github.com/typex1/lambda-refarch-imagerecognition not working. Can you provide the correct repo.
> 
> Thanks

Hi there, I have re-published my repo, please refer to the repo link above!
