### ISSUE TITLE
node10 does not include ImageMagick

### ISSUE THREAD

**Issue by magic7s** [aws-samples/lambda-refarch-imagerecognition#24]
After updating lambda functions to node10, execution fails due to following error. Assuming that node8 includes dependencies and node10 does not. 

**photo-sharing-backend-ExtractImageMetadataFunction-WO8YHMQB5V98**
```
2020-02-17T17:53:52.893Z	9e746276-c1f2-45ff-a0f1-2ef293f8fdd4	ERROR	Invoke Error	
{
    "errorType": "ImageIdentifyError",
    "errorMessage": {
        "errorType": "Error",
        "errorMessage": "Could not execute GraphicsMagick/ImageMagick: identify \"-ping\" \"-verbose\" \"-\" this most likely means the gm/convert binaries can't be found",
        "cause": {
            "errorType": "Error",
            "errorMessage": "Could not execute GraphicsMagick/ImageMagick: identify \"-ping\" \"-verbose\" \"-\" this most likely means the gm/convert binaries can't be found",
            "stack": [
                "Error: Could not execute GraphicsMagick/ImageMagick: identify \"-ping\" \"-verbose\" \"-\" this most likely means the gm/convert binaries can't be found",
                "    at ChildProcess.<anonymous> (/var/task/node_modules/gm/lib/command.js:232:12)",
                "    at ChildProcess.emit (events.js:198:13)",
                "    at ChildProcess.EventEmitter.emit (domain.js:448:20)",
                "    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)",
                "    at onErrorNT (internal/child_process.js:415:16)",
                "    at process._tickCallback (internal/process/next_tick.js:63:19)"
            ]
        },
        "isOperational": true,
        "stack": [
            "Error: Could not execute GraphicsMagick/ImageMagick: identify \"-ping\" \"-verbose\" \"-\" this most likely means the gm/convert binaries can't be found",
            "    at ChildProcess.<anonymous> (/var/task/node_modules/gm/lib/command.js:232:12)",
            "    at ChildProcess.emit (events.js:198:13)",
            "    at ChildProcess.EventEmitter.emit (domain.js:448:20)",
            "    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)",
            "    at onErrorNT (internal/child_process.js:415:16)",
            "    at process._tickCallback (internal/process/next_tick.js:63:19)"
        ]
    },
    "name": "ImageIdentifyError",
    "message": {
        "errorType": "Error",
        "errorMessage": "Could not execute GraphicsMagick/ImageMagick: identify \"-ping\" \"-verbose\" \"-\" this most likely means the gm/convert binaries can't be found",
        "cause": {
            "errorType": "Error",
            "errorMessage": "Could not execute GraphicsMagick/ImageMagick: identify \"-ping\" \"-verbose\" \"-\" this most likely means the gm/convert binaries can't be found",
            "stack": [
                "Error: Could not execute GraphicsMagick/ImageMagick: identify \"-ping\" \"-verbose\" \"-\" this most likely means the gm/convert binaries can't be found",
                "    at ChildProcess.<anonymous> (/var/task/node_modules/gm/lib/command.js:232:12)",
                "    at ChildProcess.emit (events.js:198:13)",
                "    at ChildProcess.EventEmitter.emit (domain.js:448:20)",
                "    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)",
                "    at onErrorNT (internal/child_process.js:415:16)",
                "    at process._tickCallback (internal/process/next_tick.js:63:19)"
            ]
        },
        "isOperational": true,
        "stack": [
            "Error: Could not execute GraphicsMagick/ImageMagick: identify \"-ping\" \"-verbose\" \"-\" this most likely means the gm/convert binaries can't be found",
            "    at ChildProcess.<anonymous> (/var/task/node_modules/gm/lib/command.js:232:12)",
            "    at ChildProcess.emit (events.js:198:13)",
            "    at ChildProcess.EventEmitter.emit (domain.js:448:20)",
            "    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)",
            "    at onErrorNT (internal/child_process.js:415:16)",
            "    at process._tickCallback (internal/process/next_tick.js:63:19)"
        ]
    },
    "stack": [
        "Error",
        "    at Object.<anonymous> (/var/task/index.js:40:32)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Module.require (internal/modules/cjs/loader.js:692:17)",
        "    at require (internal/modules/cjs/helpers.js:25:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:75:12)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)"
    ]
}
```

**Comment by angelarw** [comment]
thanks for calling it out. i will work on this asap

**Comment by angelarw** [comment]
i updated the template in the latest commit to master. let me know if it works for you now
